### ISSUE TITLE
[1.20.1] Fire Resistance and other similar effects don't block heat gain.

### ISSUE THREAD

**Issue by Reshy** [TheDeathlyCow/scorchful#60] opened 2024-05-06 08:37 UTC
**Describe the bug**
If you drink a potion of fire resistance or gain it through another mod you still accumulate heat and suffer from heatstroke (though you don't take any damage), if you have fire resistance specifically you still get the heartbeat noise, weakness, and mining fatigue but not heat stroke and if you have fire resistance through any other source you get heatstroke as well.

**To Reproduce**
1. Drink Fire Resistance
2. Stand on Magma
3.  Accumulate non-lethal fire stacks

**Expected behavior**
If you're immune to fire you should be immune to heatstroke and friends.

**Game information (please complete)**
- MC Version (1.20, 1.20.1, etc): 1.20.1
- Loader (Fabric/Quilt or NeoForge with Connector):  Fabric 0.15.10

With Fire Resistance:
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/f636b21b-4257-46a3-8273-0d00f2e5c7e4)

With an alternative means to resist fire (Origins):
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/48604d26-1914-4855-91d0-48530e90b445)

**Comment by TheDeathlyCow** [comment] 2024-05-06 13:25
Thanks for your issue, however I am going to close this because this is actually working as intended! In Scorchful, I define Fire Resistance to mean resistance to heat damage, but not to heat itself. The reason for this is that if fire resistance gave complete immunity to all heat increases, you could essentially make this entire mod obsolete by brewing a few cheap potions and drinking them every 8 minutes. That's not to say fire resistance is completely useless against heat though. As you have noted, it does protect you from overheating damage. Fire resistance also slows down the amount of heat you gain from being on fire quite a lot (and you can configure this). But again, it only provides some protection, not complete protection.

**Closed** 2024-05-06 13:26 UTC
Labels: bug

**Comment by TheDeathlyCow** [comment] 2024-05-06 13:32
However, your note about Fire Resistance from Origins not blocking Heat Stroke is a valid bug. That should probably be opened as a separate issue, though, as this one is focused on fire resistance blocking all heat and heat effects in general, not just heat stroke.
